version: '3.7'

services:
  dind:
    image: docker:dind
    ports:
      - "0.0.0.0:6445:6445"   # kube-apiserver
      - "0.0.0.0:30080:80"    # traefik
      - "0.0.0.0:31080:31080" # argocd 
      - "0.0.0.0:30180:30180" # traefik dashboard
    volumes:
      - ./bootstrap:/bootstrap
    working_dir: /bootstrap
    privileged: true
