version: '3.7'

services:
  dind:
    image: docker:dind
    ports:
      - "0.0.0.0:6445:6445"
      - "0.0.0.0:30080:80"
      - "0.0.0.0:30180:30180"
    volumes:
      - ./bootstrap:/bootstrap
    working_dir: /bootstrap
    privileged: true
